# Generated by Django 4.2.1 on 2023-10-01 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VoterProfile',
        ),
    ]
