# Generated by Django 4.2.1 on 2023-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
